name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install the streamdeck CLI
      - name: Install streamdeck-cli
        run: |
          npm install -g @elgato/cli

      # Build the plugin
      - name: Build the plugin
        run: |
          npm run build

      # Run default validations
      - name: Validate Plugin
        run: |
          streamdeck validate net.nik-johnson.hll-computer.sdPlugin
