name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install the streamdeck CLI
      - name: Install streamdeck-cli
        run: |
          npm install -g @elgato/cli

      # Run default validations
      - name: Pack Plugin
        run: |
          streamdeck pack net.nik-johnson.hell-let-loose-artillery-calculator.sdPlugin

      - name: Create a Release
        if: ${{ success() }}
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub release create -d -a "net.nik-johnson.hell-let-loose-artillery-calculator.streamDeckPlugin" -m "${{ github.ref_name }}" "${{ github.ref }}"
