name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install the streamdeck CLI
      - name: Install streamdeck-cli
        run: |
          npm install -g @elgato/cli

      # Install dependencies
      - name: npm install
        run: |
          npm install

      # Build the plugin
      - name: Build the plugin
        run: |
          npm run build

      # Run default validations
      - name: Pack Plugin
        run: |
          streamdeck pack net.nik-johnson.hll-computer.sdPlugin

      - name: Create a Release
        if: ${{ success() }}
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" "net.nik-johnson.hll-computer.streamDeckPlugin" --draft --generate-notes
